// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnpUHl_JXM0g2SGGy_2AQ3tlD470YxFM',
    appId: '1:244634423818:android:1b631b9fe92c374564c5f3',
    messagingSenderId: '244634423818',
    projectId: 'myanmar-to-thai',
    storageBucket: 'myanmar-to-thai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_C5vIXbfnImqlQ19iUZ6DQShIiG3UE4',
    appId: '1:244634423818:ios:3e2a1d87679a6edf64c5f3',
    messagingSenderId: '244634423818',
    projectId: 'myanmar-to-thai',
    storageBucket: 'myanmar-to-thai.appspot.com',
    iosClientId: '244634423818-7dvtd8kgti6mi7u0d2vqhpt2lk6dis5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myanmarToThai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_C5vIXbfnImqlQ19iUZ6DQShIiG3UE4',
    appId: '1:244634423818:ios:3e2a1d87679a6edf64c5f3',
    messagingSenderId: '244634423818',
    projectId: 'myanmar-to-thai',
    storageBucket: 'myanmar-to-thai.appspot.com',
    iosClientId: '244634423818-7dvtd8kgti6mi7u0d2vqhpt2lk6dis5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myanmarToThai',
  );
}
